# Generated by Django 4.1.7 on 2023-02-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
